#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE ROLE '$TEST_USER' WITH
	  LOGIN
	  NOSUPERUSER
	  NOINHERIT
	  NOCREATEDB
	  NPCREATEROLE
	  NOREPLICATION
	  LOGIN PASSWORD '$TEST_PASSWORD';

	COMMENT ON ROLE '$TEST_USER IS 'Test application user.';

	CREATE DATABASE '$TEST_DATABASE'
	  WITH
	  OWNER = '$TEST_USER'
	  ENCODING = 'UTF8'
	  LC_COLLATE = 'C'
	  LC_CTYPE = 'C'
	  TABLESPACE = pg_default
	  CONNECTION LIMIT = -1
	  IS_TEMPLATE = False;
	
	COMMENT ON DATABASE '$TEST_DATABASE'
	  IS 'Test application database.';
	
	GRANT CREATE, CONNECT ON DATABASE '$TEST_DATABASE' TO '$TEST_USER';
EOSQL